%close all
figure;
subplot(2,2,1),...
plot(toutmat./86400,squeeze(Soutmat(:,1,:)),...
    toutmat./86400,squeeze(Soutmat(:,2,:)));
title('N concentrations (mmol N/m^3)')
xlabel('days since start')
legend('N_s','N_d')
%ylim([0 15])
xlabel('Yearday')
ylabel('mmol/m^3')
xlim([0 360])
grid on

PROD_SURF_SUM=(...
    bgcparams.mum./(bgcparams.kz).*...
                      log((bgcparams.kI+Ifn(bgcparams.latlight,mod(toutmat./86400,360)))./bgcparams.kI).* ...
                     (squeeze(Soutmat(:,1,:))./(bgcparams.kN+squeeze(Soutmat(:,1,:))))');
                 
EXPORT_LOSS=((aflxfn(Dfn(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinterfn(bgcparams,toutmat),mod(toutmat./86400,360)),bgcparams.delta))...
    .*bgcparams.mum./(bgcparams.kz).*...
                      log((bgcparams.kI+Ifn(bgcparams.latlight,mod(toutmat./86400,360)))./bgcparams.kI).* ...
                     (squeeze(Soutmat(:,1,:))./(bgcparams.kN+squeeze(Soutmat(:,1,:))))') - ...
                     bflxfn(Dfn(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinterfn(bgcparams,toutmat),mod(toutmat./86400,360)),(Dwinterfn(bgcparams,toutmat)-Dfn(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinterfn(bgcparams,toutmat),mod(toutmat./86400,360))),bgcparams.delta).*...
                     bgcparams.mum./(bgcparams.kz).*...
                      log((bgcparams.kI+Ifn(bgcparams.latlight,mod(toutmat./86400,360)))./bgcparams.kI).* ...
                     (squeeze(Soutmat(:,1,:))./(bgcparams.kN+squeeze(Soutmat(:,1,:))))';
PROD_SURF_LOSS=aflxfn(Dfn(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinterfn(bgcparams,toutmat),mod(toutmat./86400,360)),bgcparams.delta).*...
    PROD_SURF_SUM;

subplot(2,2,2),...
%plot(toutmat./86400,PROD_SURF_SUM.*bgcparams.Atlwidth.*bgcparams.Atllength./1e6,...
%toutmat./86400,EXPORT_LOSS.*bgcparams.Atlwidth.*bgcparams.Atllength./1e6); hold on;
plot(toutmat./86400,PROD_SURF_SUM.*86400,...
toutmat./86400,EXPORT_LOSS.*86400); hold on;
hold on;
plot(toutmat./86400,ones(length(toutmat),1).*nanmean(PROD_SURF_SUM).*86400,'b--'); 
plot(toutmat./86400,ones(length(toutmat),1).*nanmean(EXPORT_LOSS).*86400,'r--'); 

title('Surface nutrient consumption and export')
legend('PROD','(a-b)PROD','annual mean PROD', 'annual mean (a-b)PROD')
xlabel('Yearday')
xlim([0 360])
%ylabel('kmol/s')
ylabel('mmol/m^2/d')
grid on

Dwinter=Dwinterfn(bgcparams,toutmat);
Dnow=Dfn(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinter,mod(toutmat./86400,360));
ven=venfn(bgcparams,toutmat);
wen=dDdtfn_disc(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinter,mod(toutmat./86400,360))...
    -ven.*Dnow./bgcparams.Atllength;

ENT2=-wen.*heaviside(wen)./Dnow.*(squeeze(Soutmat(1,1,:)-Soutmat(1,2,:))');
LMIX2 =-(bgcparams.kappah./(bgcparams.Atllength).^2).*(squeeze(Soutmat(1,1,:))'-bgcparams.Nsub);
LADV2 = -(ven./(bgcparams.Atllength).*heaviside(ven)).*(squeeze(Soutmat(1,1,:))'-bgcparams.Nsub);
VMIX2=  -(bgcparams.kappazML./Dnow).*((squeeze(Soutmat(1,1,:)-Soutmat(1,2,:))'))./Dnow;

subplot(2,2,3),...
%plot(toutmat./86400,PROD_SURF_SUM.*bgcparams.Atlwidth.*bgcparams.Atllength./1e6,...
%toutmat./86400,EXPORT_LOSS.*bgcparams.Atlwidth.*bgcparams.Atllength./1e6); hold on;
plot(toutmat./86400,-PROD_SURF_LOSS.*86400./Dnow,...
toutmat./86400,ENT2.*86400,...
toutmat./86400,LADV2.*86400,...
toutmat./86400,LMIX2.*86400,...
toutmat./86400,VMIX2.*86400,...
toutmat./86400,-PROD_SURF_LOSS.*86400./Dnow+ENT2.*86400+LADV2.*86400+LMIX2.*86400+VMIX2.*86400,'k-'); hold on;
%0.5.*(toutmat(2:end)+toutmat(1:end-1))./86400,(0.5.*(Dnow(2:end)'+Dnow(1:end-1)').*diff(squeeze(Soutmat(1,1,:)),1,1))./8.7805,...
hold on;
title('Surface nutrient concentration budget')
legend('aPROD','ENT','LADV','LMIX','VMIX','dN_s/dt','location','northwest')
xlabel('Yearday')
xlim([0 360])
%ylabel('kmol/s')
ylabel('mmol/m^3/d')
ylim([-.15 .15])
grid on

subplot(2,2,4),...
plot(toutmat./86400,-PROD_SURF_LOSS.*86400,...
toutmat./86400,ENT2.*86400.*Dnow,...
toutmat./86400,LADV2.*86400.*Dnow,...
toutmat./86400,LMIX2.*86400.*Dnow,...
toutmat./86400,VMIX2.*86400.*Dnow,...
toutmat./86400,-PROD_SURF_LOSS.*86400+ENT2.*86400.*Dnow+LADV2.*86400.*Dnow+LMIX2.*86400.*Dnow+VMIX2.*86400.*Dnow,'k-'); hold on;
%0.5.*(toutmat(2:end)+toutmat(1:end-1))./86400,(0.5.*(Dnow(2:end)'+Dnow(1:end-1)').*diff(squeeze(Soutmat(1,1,:)),1,1))./8.7805,...
hold on;
title('Depth-integrated surface-layer nutrient budget')
legend('aPROD','ENT','LADV','LMIX','VMIX','dN_s/dt','location','northwest')
xlabel('Yearday')
xlim([0 360])
%ylabel('kmol/s')
ylabel('mmol/m^2/d')
ylim([-10 10])
grid on
set(gcf,'color','w')