%close all
figure;
subplot(2,1,1),...
plot(toutmat./86400,smooth(squeeze(Soutmat(:,1,:)),30),...
    toutmat./86400,smooth(squeeze(Soutmat(:,2,:)),30));
title('N concentrations (mmol N/m^3)')
xlabel('days since start')
legend('N_s','N_d')
%ylim([0 15])
xlabel('Yearday')
ylabel('mmol/m^3')
xlim([15 345])
grid on

PROD_SURF_SUM=(...
    bgcparams.mum./(bgcparams.kz).*...
                      log((bgcparams.kI+Ifn(bgcparams.latlight,mod(toutmat./86400,360)))./bgcparams.kI).* ...
                     (squeeze(Soutmat(:,1,:))./(bgcparams.kN+squeeze(Soutmat(:,1,:))))');
                 
EXPORT_LOSS=((aflxfn(Dfn(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinterfn(bgcparams,toutmat),mod(toutmat./86400,360)),bgcparams.delta))...
    .*bgcparams.mum./(bgcparams.kz).*...
                      log((bgcparams.kI+Ifn(bgcparams.latlight,mod(toutmat./86400,360)))./bgcparams.kI).* ...
                     (squeeze(Soutmat(:,1,:))./(bgcparams.kN+squeeze(Soutmat(:,1,:))))') - ...
                     bflxfn(Dfn(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinterfn(bgcparams,toutmat),mod(toutmat./86400,360)),(Dwinterfn(bgcparams,toutmat)-Dfn(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinterfn(bgcparams,toutmat),mod(toutmat./86400,360))),bgcparams.delta).*...
                     bgcparams.mum./(bgcparams.kz).*...
                      log((bgcparams.kI+Ifn(bgcparams.latlight,mod(toutmat./86400,360)))./bgcparams.kI).* ...
                     (squeeze(Soutmat(:,1,:))./(bgcparams.kN+squeeze(Soutmat(:,1,:))))';
PROD_SURF_LOSS=aflxfn(Dfn(bgcparams.Db,(bgcparams.Dmldfrac).*Dwinterfn(bgcparams,toutmat),mod(toutmat./86400,360)),bgcparams.delta).*...
    PROD_SURF_SUM;

subplot(2,1,2),...
%plot(toutmat./86400,PROD_SURF_SUM.*bgcparams.Atlwidth.*bgcparams.Atllength./1e6,...
%toutmat./86400,EXPORT_LOSS.*bgcparams.Atlwidth.*bgcparams.Atllength./1e6); hold on;
plot(toutmat./86400,smooth(PROD_SURF_SUM.*86400,30),...
toutmat./86400,smooth(EXPORT_LOSS.*86400,30)); hold on;
hold on;
plot(toutmat./86400,ones(length(toutmat),1).*nanmean(PROD_SURF_SUM).*86400,'b--'); 
plot(toutmat./86400,ones(length(toutmat),1).*nanmean(EXPORT_LOSS).*86400,'r--'); 

title('Surface nutrient consumption and export')
legend('PROD','(a-b)PROD','annual mean PROD', 'annual mean (a-b)PROD')
xlabel('Yearday')
xlim([15 345])
%ylabel('kmol/s')
ylabel('mmol/m^2/d')
grid on


set(gcf,'color','w')